# Generated by Django 4.1.4 on 2022-12-30 18:26

import cards.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=8)),
                ('number', cards.fields.CardNumberField(editable=False, max_length=8, null=True, unique=True)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(blank=True, choices=[('A', 'A'), ('N', 'N'), ('E', 'E')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
        ),
    ]
