# Generated by Django 4.1.4 on 2023-01-02 14:53

import cards.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_date_of_issue_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=cards.fields.CardNumberField(editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
